class WeaponTypes:
    assault_rifle = "Assault Rifle"
    light_machine_gun = "Light Machine Gun"
    melee = "Melee Weapon"
    pistol = "Pistol"
    revolver = "Revolver"
    rifle = "Rifle"
    shotgun = "Shotgun"
    sniper = "Sniper Rifle"
    submachine_gun = "Sub-Machine Gun"