class ItemTags:
    csharp_checkpoint = "C#: Checkpoint"
    csharp_item_id = "C#: ItemID"
    csharp_loot_chance = "C#: Loot Chance"
    csharp_loot_table = "C#: LootTable"
    csharp_printer = "C#: Printer"
    csharp_rubberbanding = "C#: Rubberbanding"
    csharp_sulf = "C#: Sulf"
    csharp_vendor_table_extension = "C#: VendorTable extension"
    csharp_charity = "C#: Charity"
    csharp_recipe_unlock = "C#: Recipe unlock"
    csharp_recurring = "C#: Recurring"

    group_charity = "Charity"
    group_explosive = "Explosives"
    group_food = "Food"
    group_ingredients = "Ingredients"
    group_cookbooks = "Recipes"
    group_recurring_donations = "Recurring Donations"
    group_repeatable = "Repeatable"
    group_scroll = "Scrolls"
    group_service_stations = "Service stations"
    group_shortcut = "Shortcuts"
    group_storage = "Storages"
    group_useful = "Useful"
    group_valuables = "Valuables"

    unused_csharp_door_lock = "Unused: C# Door lock"
    unused_csharp_explosives_lock = "Unused: C# Explosives lock"
    unused_csharp_quest_lock = "Unused: C# Quest lock"
    unused_csharp_rank_lock = "Unused: C# Rank lock"
    unused_group_door_lock = "Unused: Door lock"